version: "3.5"

services:
  sport_app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: "sport_app"
    depends_on:
      - db
    ports:
      - "82:81"
    networks:
      - atanapi_network
  db:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atanapi_network

volumes:
  postgres_data:

networks:
  atanapi_network:
    external: true
