version: "3.5"

services:
  sport_app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: "sport_app"
    ports:
      - "82:81"
    networks:
      - network-local

  mysql:
    image: mysql:latest
    container_name: sport_mysql
    platform: linux/x86_64
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network-local

volumes:
  mysql_data:

networks:
  network-local:
    external: true
